<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DeputadosSeeder extends Seeder
{
    public function run(): void
    {

        DB::table('deputados')->insert([
            [
                'deputado_id' => 1001,
                'nome' => 'Ana Clara Silva',
                'sigla_partido' => 'PT',
                'sigla_uf' => 'SP',
                'sigla_sexo' => 'F',
                'email' => 'ana.silva@camara.leg.br',
                'uri' => 'https://camara.leg.br/deputados/1001',
                'data_nascimento' => '1980-05-12',
                'municipio_nascimento' => 'São Paulo',
                'uf_nascimento' => 'SP',
                'rede_social' => json_encode([
                    'twitter' => '@anaSilva',
                    'instagram' => '@ana.silva',
                ]),
                'url_website' => 'https://anasilva.com.br',
                'condicao_eleitoral' => 'Titular',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5501',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1002,
                'nome' => 'Bruno Almeida',
                'sigla_partido' => 'PSDB',
                'sigla_uf' => 'RJ',
                'sigla_sexo' => 'M',
                'email' => 'bruno.almeida@psdb.org.br',
                'uri' => 'https://camara.leg.br/deputados/1002',
                'data_nascimento' => '1975-09-30',
                'municipio_nascimento' => 'Rio de Janeiro',
                'uf_nascimento' => 'RJ',
                'rede_social' => json_encode([
                    'twitter' => '@brunoAlmeida',
                    'instagram' => '@bruno.almeida',
                ]),
                'url_website' => 'https://brunoalmeida.org',
                'condicao_eleitoral' => 'Titular',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5502',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1003,
                'nome' => 'Carla Moura',
                'sigla_partido' => 'PL',
                'sigla_uf' => 'MG',
                'sigla_sexo' => 'F',
                'email' => 'carla.moura@pl.org.br',
                'uri' => 'https://camara.leg.br/deputados/1003',
                'data_nascimento' => '1988-03-18',
                'municipio_nascimento' => 'Belo Horizonte',
                'uf_nascimento' => 'MG',
                'rede_social' => json_encode([
                    'twitter' => '@carlaMoura',
                    'instagram' => '@carlamoura',
                ]),
                'url_website' => 'https://carlamoura.com.br',
                'condicao_eleitoral' => 'Suplente',
                'situacao' => 'Licenciado',
                'descricao_status' => 'Em licença',
                'telefone' => '(61) 3215-5503',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1004,
                'nome' => 'Daniel Souza',
                'sigla_partido' => 'MDB',
                'sigla_uf' => 'RS',
                'sigla_sexo' => 'M',
                'email' => 'daniel.souza@mdb.org.br',
                'uri' => 'https://camara.leg.br/deputados/1004',
                'data_nascimento' => '1969-11-22',
                'municipio_nascimento' => 'Salvador',
                'uf_nascimento' => 'BA',
                'rede_social' => json_encode([
                    'twitter' => '@danielSouza',
                    'instagram' => '@danielsouza',
                ]),
                'url_website' => 'https://danielsouza.net',
                'condicao_eleitoral' => 'Titular',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5504',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1005,
                'nome' => 'Eduarda Lima',
                'sigla_partido' => 'PDT',
                'sigla_uf' => 'BA',
                'sigla_sexo' => 'F',
                'email' => 'eduarda.lima@pdt.org.br',
                'uri' => 'https://camara.leg.br/deputados/1005',
                'data_nascimento' => '1983-07-01',
                'municipio_nascimento' => 'Curitiba',
                'uf_nascimento' => 'PR',
                'rede_social' => json_encode([
                    'twitter' => '@eduardaLima',
                    'instagram' => '@eduardalima',
                ]),
                'url_website' => 'https://eduardalima.com',
                'condicao_eleitoral' => 'Titular',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5505',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1006,
                'nome' => 'Felipe Rocha',
                'sigla_partido' => 'PSOL',
                'sigla_uf' => 'PE',
                'sigla_sexo' => 'M',
                'email' => 'felipe.rocha@psol.org.br',
                'uri' => 'https://camara.leg.br/deputados/1006',
                'data_nascimento' => '1986-02-17',
                'municipio_nascimento' => 'Porto Alegre',
                'uf_nascimento' => 'RS',
                'rede_social' => json_encode([
                    'twitter' => '@felipeRocha',
                    'instagram' => '@feliperocha',
                ]),
                'url_website' => 'https://feliperocha.org',
                'condicao_eleitoral' => 'Suplente',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5506',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1007,
                'nome' => 'Gabriela Duarte',
                'sigla_partido' => 'DEM',
                'sigla_uf' => 'PR',
                'sigla_sexo' => 'F',
                'email' => 'gabriela.duarte@dem.org.br',
                'uri' => 'https://camara.leg.br/deputados/1007',
                'data_nascimento' => '1978-08-14',
                'municipio_nascimento' => 'Recife',
                'uf_nascimento' => 'PE',
                'rede_social' => json_encode([
                    'twitter' => '@gabrielaDuarte',
                    'instagram' => '@gabrieladuarte',
                ]),
                'url_website' => 'https://gabrieladuarte.com.br',
                'condicao_eleitoral' => 'Titular',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5507',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1008,
                'nome' => 'Henrique Castro',
                'sigla_partido' => 'PSD',
                'sigla_uf' => 'CE',
                'sigla_sexo' => 'M',
                'email' => 'henrique.castro@psd.org.br',
                'uri' => 'https://camara.leg.br/deputados/1008',
                'data_nascimento' => '1982-12-25',
                'municipio_nascimento' => 'Goiânia',
                'uf_nascimento' => 'GO',
                'rede_social' => json_encode([
                    'twitter' => '@henriqueCastro',
                    'instagram' => '@henriquecastro',
                ]),
                'url_website' => 'https://henriquecastro.com',
                'condicao_eleitoral' => 'Titular',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5508',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1009,
                'nome' => 'Isabela Teixeira',
                'sigla_partido' => 'REDE',
                'sigla_uf' => 'AM',
                'sigla_sexo' => 'F',
                'email' => 'isabela.teixeira@rede.org.br',
                'uri' => 'https://camara.leg.br/deputados/1009',
                'data_nascimento' => '1990-06-08',
                'municipio_nascimento' => 'Fortaleza',
                'uf_nascimento' => 'CE',
                'rede_social' => json_encode([
                    'twitter' => '@isabelaTeixeira',
                    'instagram' => '@isabelateixeira',
                ]),
                'url_website' => 'https://isabelateixeira.org',
                'condicao_eleitoral' => 'Suplente',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5509',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1010,
                'nome' => 'João Pedro Ramos',
                'sigla_partido' => 'NOVO',
                'sigla_uf' => 'SC',
                'sigla_sexo' => 'M',
                'email' => 'joao.ramos@novo.org.br',
                'uri' => 'https://camara.leg.br/deputados/1010',
                'data_nascimento' => '1972-04-03',
                'municipio_nascimento' => 'Florianópolis',
                'uf_nascimento' => 'SC',
                'rede_social' => json_encode([
                    'twitter' => '@joaoRamos',
                    'instagram' => '@joaoramos',
                ]),
                'url_website' => 'https://joaoramos.com.br',
                'condicao_eleitoral' => 'Titular',
                'situacao' => 'Exercício',
                'descricao_status' => 'Em exercício',
                'telefone' => '(61) 3215-5510',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('despesas')->insert([
            [
                'deputado_id' => 1006,
                'tipo_despesa' => 'Restaurantes',
                'valor' => 1674.8,
                'fornecedor' => 'Restaurante Dom',
                'data_despesa' => '2025-05-30',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1001,
                'tipo_despesa' => 'Locação de Veículo',
                'valor' => 4484.06,
                'fornecedor' => 'Unidas',
                'data_despesa' => '2025-07-11',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1003,
                'tipo_despesa' => 'Eventos e Seminários',
                'valor' => 220.05,
                'fornecedor' => 'Seminários Brasil',
                'data_despesa' => '2025-06-27',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1006,
                'tipo_despesa' => 'Serviços Postais',
                'valor' => 2987.81,
                'fornecedor' => 'Correios',
                'data_despesa' => '2025-06-21',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1005,
                'tipo_despesa' => 'Locação de Veículo',
                'valor' => 2636.92,
                'fornecedor' => 'Movida',
                'data_despesa' => '2025-06-28',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1007,
                'tipo_despesa' => 'Restaurantes',
                'valor' => 2285.66,
                'fornecedor' => 'Churrascaria Fogo Vivo',
                'data_despesa' => '2025-06-29',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1010,
                'tipo_despesa' => 'Hospedagem',
                'valor' => 2590.55,
                'fornecedor' => 'Blue Tree Towers',
                'data_despesa' => '2025-07-23',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1002,
                'tipo_despesa' => 'Eventos e Seminários',
                'valor' => 2413.25,
                'fornecedor' => 'Organiza Eventos',
                'data_despesa' => '2025-07-17',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1003,
                'tipo_despesa' => 'Telefonia',
                'valor' => 779.41,
                'fornecedor' => 'Tim',
                'data_despesa' => '2025-06-28',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1001,
                'tipo_despesa' => 'Passagens Aéreas',
                'valor' => 4608.45,
                'fornecedor' => 'GOL',
                'data_despesa' => '2025-06-06',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1004,
                'tipo_despesa' => 'Combustível',
                'valor' => 3931.88,
                'fornecedor' => 'Petrobras',
                'data_despesa' => '2025-06-18',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1003,
                'tipo_despesa' => 'Hospedagem',
                'valor' => 2473.01,
                'fornecedor' => 'Hotel Nacional',
                'data_despesa' => '2025-06-09',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1010,
                'tipo_despesa' => 'Aluguel de Escritório',
                'valor' => 4694.59,
                'fornecedor' => 'Centro Imóveis',
                'data_despesa' => '2025-06-04',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1006,
                'tipo_despesa' => 'Serviços de Consultoria',
                'valor' => 3362.41,
                'fornecedor' => 'Estratégia Brasil',
                'data_despesa' => '2025-06-18',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1005,
                'tipo_despesa' => 'Eventos e Seminários',
                'valor' => 3006.67,
                'fornecedor' => 'Seminários Brasil',
                'data_despesa' => '2025-07-02',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1001,
                'tipo_despesa' => 'Serviços Postais',
                'valor' => 1598.57,
                'fornecedor' => 'Correios',
                'data_despesa' => '2025-07-23',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1008,
                'tipo_despesa' => 'Hospedagem',
                'valor' => 3281.65,
                'fornecedor' => 'Blue Tree Towers',
                'data_despesa' => '2025-07-10',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1007,
                'tipo_despesa' => 'Divulgação Parlamentar',
                'valor' => 4512.58,
                'fornecedor' => 'Agência Criativa DF',
                'data_despesa' => '2025-06-16',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1005,
                'tipo_despesa' => 'Aluguel de Escritório',
                'valor' => 4187.77,
                'fornecedor' => 'Imobiliária DF',
                'data_despesa' => '2025-06-02',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1008,
                'tipo_despesa' => 'Serviços de Consultoria',
                'valor' => 3420.73,
                'fornecedor' => 'Gestão Pública Ltda',
                'data_despesa' => '2025-07-17',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1009,
                'tipo_despesa' => 'Restaurantes',
                'valor' => 3823.97,
                'fornecedor' => 'Bistro Brasília',
                'data_despesa' => '2025-07-06',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1007,
                'tipo_despesa' => 'Telefonia',
                'valor' => 818.23,
                'fornecedor' => 'Claro',
                'data_despesa' => '2025-07-25',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1009,
                'tipo_despesa' => 'Eventos e Seminários',
                'valor' => 4264.83,
                'fornecedor' => 'Organiza Eventos',
                'data_despesa' => '2025-07-10',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1008,
                'tipo_despesa' => 'Combustível',
                'valor' => 2847.06,
                'fornecedor' => 'Posto Shell',
                'data_despesa' => '2025-06-24',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1004,
                'tipo_despesa' => 'Manutenção de Escritório',
                'valor' => 4252.62,
                'fornecedor' => 'Serviços Gerais Sudoeste',
                'data_despesa' => '2025-07-01',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1003,
                'tipo_despesa' => 'Serviços de Consultoria',
                'valor' => 2727.31,
                'fornecedor' => 'Consultoria ProPolítica',
                'data_despesa' => '2025-06-23',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1009,
                'tipo_despesa' => 'Hospedagem',
                'valor' => 3324.89,
                'fornecedor' => 'Hotel Nacional',
                'data_despesa' => '2025-07-03',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1007,
                'tipo_despesa' => 'Serviços Postais',
                'valor' => 2206.88,
                'fornecedor' => 'Correios',
                'data_despesa' => '2025-07-21',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1003,
                'tipo_despesa' => 'Locação de Veículo',
                'valor' => 3937.93,
                'fornecedor' => 'Movida',
                'data_despesa' => '2025-07-01',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1001,
                'tipo_despesa' => 'Hospedagem',
                'valor' => 3113.31,
                'fornecedor' => 'Blue Tree Towers',
                'data_despesa' => '2025-07-24',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1002,
                'tipo_despesa' => 'Manutenção de Escritório',
                'valor' => 4616.83,
                'fornecedor' => 'Serviços Gerais Sudoeste',
                'data_despesa' => '2025-06-25',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1006,
                'tipo_despesa' => 'Eventos e Seminários',
                'valor' => 3845.42,
                'fornecedor' => 'Organiza Eventos',
                'data_despesa' => '2025-07-04',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1004,
                'tipo_despesa' => 'Divulgação Parlamentar',
                'valor' => 4689.42,
                'fornecedor' => 'Gráfica Centro Norte',
                'data_despesa' => '2025-07-20',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1010,
                'tipo_despesa' => 'Telefonia',
                'valor' => 496.7,
                'fornecedor' => 'Claro',
                'data_despesa' => '2025-06-29',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1008,
                'tipo_despesa' => 'Passagens Aéreas',
                'valor' => 4231.11,
                'fornecedor' => 'LATAM',
                'data_despesa' => '2025-06-24',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1002,
                'tipo_despesa' => 'Restaurantes',
                'valor' => 4072.45,
                'fornecedor' => 'Bistro Brasília',
                'data_despesa' => '2025-07-16',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1004,
                'tipo_despesa' => 'Passagens Aéreas',
                'valor' => 2293.87,
                'fornecedor' => 'AZUL',
                'data_despesa' => '2025-07-03',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1006,
                'tipo_despesa' => 'Divulgação Parlamentar',
                'valor' => 4911.23,
                'fornecedor' => 'Agência Criativa DF',
                'data_despesa' => '2025-06-03',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1007,
                'tipo_despesa' => 'Manutenção de Escritório',
                'valor' => 3854.73,
                'fornecedor' => 'Assistência Brasília Tech',
                'data_despesa' => '2025-06-26',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1010,
                'tipo_despesa' => 'Combustível',
                'valor' => 4649.16,
                'fornecedor' => 'Posto BR',
                'data_despesa' => '2025-06-01',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1005,
                'tipo_despesa' => 'Restaurantes',
                'valor' => 3206.68,
                'fornecedor' => 'Churrascaria Fogo Vivo',
                'data_despesa' => '2025-06-12',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1009,
                'tipo_despesa' => 'Passagens Aéreas',
                'valor' => 2469.12,
                'fornecedor' => 'AZUL',
                'data_despesa' => '2025-07-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1002,
                'tipo_despesa' => 'Aluguel de Escritório',
                'valor' => 4898.15,
                'fornecedor' => 'Imóveis Brasília',
                'data_despesa' => '2025-07-15',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1006,
                'tipo_despesa' => 'Hospedagem',
                'valor' => 4376.64,
                'fornecedor' => 'Hotel Nacional',
                'data_despesa' => '2025-06-12',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1004,
                'tipo_despesa' => 'Locação de Veículo',
                'valor' => 4267.17,
                'fornecedor' => 'Localiza',
                'data_despesa' => '2025-07-08',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1001,
                'tipo_despesa' => 'Serviços de Consultoria',
                'valor' => 2765.74,
                'fornecedor' => 'Gestão Pública Ltda',
                'data_despesa' => '2025-07-04',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1007,
                'tipo_despesa' => 'Aluguel de Escritório',
                'valor' => 2444.08,
                'fornecedor' => 'Imobiliária DF',
                'data_despesa' => '2025-07-19',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1005,
                'tipo_despesa' => 'Passagens Aéreas',
                'valor' => 3178.35,
                'fornecedor' => 'LATAM',
                'data_despesa' => '2025-07-15',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'deputado_id' => 1008,
                'tipo_despesa' => 'Telefonia',
                'valor' => 221.33,
                'fornecedor' => 'Vivo',
                'data_despesa' => '2025-06-10',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);

        DB::table('situacoes')->insert([
            [
                'id' => 1,
                'descricao' => 'Em exercício',
                'sigla' => 'EXC',
                'created_at' => Carbon::parse('2025-07-01 08:00:00'),
                'updated_at' => Carbon::parse('2025-07-01 08:00:00'),
            ],
            [
                'id' => 2,
                'descricao' => 'Licenciado',
                'sigla' => 'LIC',
                'created_at' => Carbon::parse('2025-07-01 08:00:00'),
                'updated_at' => Carbon::parse('2025-07-01 08:00:00'),
            ],
            [
                'id' => 3,
                'descricao' => 'Falecido',
                'sigla' => 'FAL',
                'created_at' => Carbon::parse('2025-07-01 08:00:00'),
                'updated_at' => Carbon::parse('2025-07-01 08:00:00'),
            ],
            [
                'id' => 4,
                'descricao' => 'Afastado',
                'sigla' => 'AFS',
                'created_at' => Carbon::parse('2025-07-01 08:00:00'),
                'updated_at' => Carbon::parse('2025-07-01 08:00:00'),
            ],
            [
                'id' => 5,
                'descricao' => 'Empossado',
                'sigla' => 'EMP',
                'created_at' => Carbon::parse('2025-07-01 08:00:00'),
                'updated_at' => Carbon::parse('2025-07-01 08:00:00'),
            ],
        ]);
    }
}
